<a href="https://colab.research.google.com/github/akiwelekar/MLModels/blob/master/MLR_OLS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
x = np.array([[1,15,72],
             [1,22,88],
             [1,16,92],
             [1,18,78],
             [1,30,88]])
y=np.array([[55],
            [68],
            [62],
            [65],
            [72]])
print(x)
print(y)

xt = x.transpose()
print(xt)
s1= xt.dot(x)
print(s1)
s2 = xt.dot(y)
print(s2)
s3= np.linalg.inv(s1)
print (s3)
beta= s3.dot(s2)
print(beta)


[[ 1 15 72]
 [ 1 22 88]
 [ 1 16 92]
 [ 1 18 78]
 [ 1 30 88]]
[[55]
 [68]
 [62]
 [65]
 [72]]
[[ 1  1  1  1  1]
 [15 22 16 18 30]
 [72 88 92 78 88]]
[[    5   101   418]
 [  101  2189  8532]
 [  418  8532 35220]]
[[  322]
 [ 6643]
 [27054]]
[[ 2.59636640e+01  5.52644921e-02 -3.21531181e-01]
 [ 5.52644921e-02  8.30536710e-03 -2.66785775e-03]
 [-3.21531181e-01 -2.66785775e-03  4.49069268e-03]]
[[28.71725537]
 [ 0.79149666]
 [ 0.23558029]]
